import { Partnership } from './types'

export const MOCK_PARTNERSHIPS: Partnership[] = [
  {
    id: 'mock-1',
    created_at: '2026-05-15T00:00:00Z',
    updated_at: '2026-05-15T00:00:00Z',
    make: 'Cessna',
    model: '172S Skyhawk',
    year: 2004,
    registration: 'N12345',
    home_airport: 'KAUS',
    airport_name: 'Austin-Bergstrom International',
    city: 'Austin',
    state: 'TX',
    lat: 30.1975,
    lng: -97.6664,
    share_type: '1/3',
    shares_available: 1,
    total_shares: 3,
    buy_in_price: 18000,
    monthly_fixed: 320,
    hourly_wet: 85,
    min_hours: 150,
    ratings_required: ['PPL'],
    scheduling_system: 'FlyingClub',
    title: '1/3 Share Available — 2004 C172S, Austin TX (KAUS)',
    description: 'Well-maintained 2004 Cessna 172S with Garmin G1000 glass cockpit. 3,200 TTAF, engine at 650 SMOH. Annual due in March. Two current partners — both instrument rated, fly ~50 hrs/year each. Hangared at KAUS. Looking for a responsible pilot to round out the group. Message for current squawk sheet.',
    images: null,
    contact_name: 'David M.',
    contact_email: 'david@example.com',
    contact_method: 'email',
    contact_phone: null,
    status: 'active',
    poster_id: null,
    source_url: null,
    image_is_placeholder: true,
  },
  {
    id: 'mock-2',
    created_at: '2026-05-20T00:00:00Z',
    updated_at: '2026-05-20T00:00:00Z',
    make: 'Piper',
    model: 'PA-28-181 Archer',
    year: 1999,
    registration: 'N8876K',
    home_airport: 'KADS',
    airport_name: 'Addison Airport',
    city: 'Dallas',
    state: 'TX',
    lat: 32.9686,
    lng: -96.8364,
    share_type: '1/2',
    shares_available: 1,
    total_shares: 2,
    buy_in_price: 25000,
    monthly_fixed: 450,
    hourly_wet: 90,
    min_hours: 200,
    ratings_required: ['PPL', 'IFR'],
    scheduling_system: 'Google Calendar',
    title: 'IFR-equipped Archer 1/2 Share — KADS Dallas',
    description: 'Selling a half share in my 1999 Piper Archer. Full IFR panel with Garmin 430W, autopilot, and fresh IFR cert. 2,800 TTAF, engine at 1,100 SMOH. Always hangared at Addison. I fly primarily weekdays so looking for a partner who prefers weekends. $450/mo covers hangar + insurance. Wet rate includes fuel and oil.',
    images: null,
    contact_name: 'Sarah K.',
    contact_email: 'sarah@example.com',
    contact_method: 'email',
    contact_phone: null,
    status: 'active',
    poster_id: null,
    source_url: null,
    image_is_placeholder: true,
  },
  {
    id: 'mock-3',
    created_at: '2026-06-01T00:00:00Z',
    updated_at: '2026-06-01T00:00:00Z',
    make: 'Cirrus',
    model: 'SR22',
    year: 2007,
    registration: 'N441SR',
    home_airport: 'KFXE',
    airport_name: 'Fort Lauderdale Executive',
    city: 'Fort Lauderdale',
    state: 'FL',
    lat: 26.1973,
    lng: -80.1707,
    share_type: '1/4',
    shares_available: 1,
    total_shares: 4,
    buy_in_price: 32000,
    monthly_fixed: 400,
    hourly_wet: 130,
    min_hours: 300,
    ratings_required: ['PPL', 'IFR', 'Cirrus Transition'],
    scheduling_system: 'FlyingClub',
    title: 'SR22 — 1/4 Share Opening at KFXE',
    description: '2007 Cirrus SR22 with Avidyne glass and CAPS parachute system. 2,100 TTAF. Current partner is relocating so we have one share available. Remaining three partners are experienced, instrument-rated pilots. This is a well-organized ownership group with a detailed partnership agreement. Cirrus transition course required if not already completed.',
    images: null,
    contact_name: 'Marcus T.',
    contact_email: 'marcus@example.com',
    contact_method: 'both',
    contact_phone: '954-555-0182',
    status: 'active',
    poster_id: null,
    source_url: null,
    image_is_placeholder: true,
  },
  {
    id: 'mock-4',
    created_at: '2026-06-05T00:00:00Z',
    updated_at: '2026-06-05T00:00:00Z',
    make: 'Van\'s',
    model: 'RV-7A',
    year: 2015,
    registration: 'N750RV',
    home_airport: 'KPAO',
    airport_name: 'Palo Alto Airport',
    city: 'Palo Alto',
    state: 'CA',
    lat: 37.4611,
    lng: -122.1151,
    share_type: '1/2',
    shares_available: 1,
    total_shares: 2,
    buy_in_price: 40000,
    monthly_fixed: 280,
    hourly_wet: 70,
    min_hours: 250,
    ratings_required: ['PPL'],
    scheduling_system: 'Other',
    title: 'RV-7A Half Share — Palo Alto (KPAO), Low Operating Cost',
    description: 'Sharing my 2015 Van\'s RV-7A. 380 TTAF total. IO-360 engine at 380 SMOH (factory new). Garmin G3X with autopilot, ADS-B in/out. 160 knots cruise on 8 gph — cheapest fast airplane you\'ll find. 280/mo covers hangar + insurance split. Tiedown at KPAO. Ideal for a Bay Area pilot who wants speed without the SR22 price tag.',
    images: null,
    contact_name: 'James L.',
    contact_email: 'james@example.com',
    contact_method: 'email',
    contact_phone: null,
    status: 'active',
    poster_id: null,
    source_url: null,
    image_is_placeholder: true,
  },
]
