import { Partnership, PartnershipSeeker } from './types'

export const MOCK_PARTNERSHIPS: Partnership[] = [
  {
    id: 'mock-1',
    created_at: '2026-05-15T00:00:00Z',
    updated_at: '2026-05-15T00:00:00Z',
    make: 'Cessna',
    model: '172S Skyhawk',
    year: 2004,
    registration: 'N12345',
    home_airport: 'KAUS',
    airport_name: 'Austin-Bergstrom International',
    city: 'Austin',
    state: 'TX',
    lat: 30.1975,
    lng: -97.6664,
    share_type: '1/3',
    shares_available: 1,
    total_shares: 3,
    buy_in_price: 18000,
    monthly_fixed: 320,
    hourly_wet: 85,
    min_hours: 150,
    ratings_required: ['PPL'],
    scheduling_system: 'FlyingClub',
    title: '1/3 Share Available — 2004 C172S, Austin TX (KAUS)',
    description: 'Well-maintained 2004 Cessna 172S with Garmin G1000 glass cockpit. 3,200 TTAF, engine at 650 SMOH. Annual due in March. Two current partners — both instrument rated, fly ~50 hrs/year each. Hangared at KAUS. Looking for a responsible pilot to round out the group. Message for current squawk sheet.',
    images: null,
    contact_name: 'David M.',
    contact_email: 'david@example.com',
    contact_method: 'email',
    contact_phone: null,
    status: 'active',
    poster_id: null,
    source_url: null,
    image_is_placeholder: true,
    posted_at: null,
    ttaf: 3200,
    smoh: 650,
    engine_type: 'Lycoming IO-360',
  },
  {
    id: 'mock-2',
    created_at: '2026-05-20T00:00:00Z',
    updated_at: '2026-05-20T00:00:00Z',
    make: 'Piper',
    model: 'PA-28-181 Archer',
    year: 1999,
    registration: 'N8876K',
    home_airport: 'KADS',
    airport_name: 'Addison Airport',
    city: 'Dallas',
    state: 'TX',
    lat: 32.9686,
    lng: -96.8364,
    share_type: '1/2',
    shares_available: 1,
    total_shares: 2,
    buy_in_price: 25000,
    monthly_fixed: 450,
    hourly_wet: 90,
    min_hours: 200,
    ratings_required: ['PPL', 'IFR'],
    scheduling_system: 'Google Calendar',
    title: 'IFR-equipped Archer 1/2 Share — KADS Dallas',
    description: 'Selling a half share in my 1999 Piper Archer. Full IFR panel with Garmin 430W, autopilot, and fresh IFR cert. 2,800 TTAF, engine at 1,100 SMOH. Always hangared at Addison. I fly primarily weekdays so looking for a partner who prefers weekends. $450/mo covers hangar + insurance. Wet rate includes fuel and oil.',
    images: null,
    contact_name: 'Sarah K.',
    contact_email: 'sarah@example.com',
    contact_method: 'email',
    contact_phone: null,
    status: 'active',
    poster_id: null,
    source_url: null,
    image_is_placeholder: true,
    posted_at: null,
    ttaf: 2800,
    smoh: 1100,
    engine_type: 'Lycoming O-360',
  },
  {
    id: 'mock-3',
    created_at: '2026-06-01T00:00:00Z',
    updated_at: '2026-06-01T00:00:00Z',
    make: 'Cirrus',
    model: 'SR22',
    year: 2007,
    registration: 'N441SR',
    home_airport: 'KFXE',
    airport_name: 'Fort Lauderdale Executive',
    city: 'Fort Lauderdale',
    state: 'FL',
    lat: 26.1973,
    lng: -80.1707,
    share_type: '1/4',
    shares_available: 1,
    total_shares: 4,
    buy_in_price: 32000,
    monthly_fixed: 400,
    hourly_wet: 130,
    min_hours: 300,
    ratings_required: ['PPL', 'IFR', 'Cirrus Transition'],
    scheduling_system: 'FlyingClub',
    title: 'SR22 — 1/4 Share Opening at KFXE',
    description: '2007 Cirrus SR22 with Avidyne glass and CAPS parachute system. 2,100 TTAF. Current partner is relocating so we have one share available. Remaining three partners are experienced, instrument-rated pilots. This is a well-organized ownership group with a detailed partnership agreement. Cirrus transition course required if not already completed.',
    images: null,
    contact_name: 'Marcus T.',
    contact_email: 'marcus@example.com',
    contact_method: 'both',
    contact_phone: '954-555-0182',
    status: 'active',
    poster_id: null,
    source_url: null,
    image_is_placeholder: true,
    posted_at: null,
    ttaf: 2100,
    smoh: null,
    engine_type: null,
  },
  {
    id: 'mock-4',
    created_at: '2026-06-05T00:00:00Z',
    updated_at: '2026-06-05T00:00:00Z',
    make: 'Van\'s',
    model: 'RV-7A',
    year: 2015,
    registration: 'N750RV',
    home_airport: 'KPAO',
    airport_name: 'Palo Alto Airport',
    city: 'Palo Alto',
    state: 'CA',
    lat: 37.4611,
    lng: -122.1151,
    share_type: '1/2',
    shares_available: 1,
    total_shares: 2,
    buy_in_price: 40000,
    monthly_fixed: 280,
    hourly_wet: 70,
    min_hours: 250,
    ratings_required: ['PPL'],
    scheduling_system: 'Other',
    title: 'RV-7A Half Share — Palo Alto (KPAO), Low Operating Cost',
    description: 'Sharing my 2015 Van\'s RV-7A. 380 TTAF total. IO-360 engine at 380 SMOH (factory new). Garmin G3X with autopilot, ADS-B in/out. 160 knots cruise on 8 gph — cheapest fast airplane you\'ll find. 280/mo covers hangar + insurance split. Tiedown at KPAO. Ideal for a Bay Area pilot who wants speed without the SR22 price tag.',
    images: null,
    contact_name: 'James L.',
    contact_email: 'james@example.com',
    contact_method: 'email',
    contact_phone: null,
    status: 'active',
    poster_id: null,
    source_url: null,
    image_is_placeholder: true,
    posted_at: null,
    ttaf: 380,
    smoh: 380,
    engine_type: 'Lycoming IO-360',
  },
]

export const MOCK_SEEKERS: PartnershipSeeker[] = [
  {
    id: 'seek-1',
    created_at: '2026-06-01T00:00:00Z',
    updated_at: '2026-06-01T00:00:00Z',
    preferred_makes: ['Cessna', 'Piper'],
    preferred_models: '172, 182, PA-28',
    min_year: 2000,
    max_year: null,
    aircraft_category: 'sel',
    max_buy_in: 20000,
    max_monthly: 400,
    max_hourly: 100,
    home_airport: 'KAUS',
    airport_name: 'Austin-Bergstrom International',
    city: 'Austin',
    state: 'TX',
    willing_to_travel_nm: 50,
    total_hours: 280,
    ratings_held: ['PPL', 'IFR'],
    preferred_share_types: ['1/3', '1/4'],
    preferred_scheduling: 'FlyingClub',
    intended_use: ['personal_travel', 'weekend_trips'],
    hours_per_month: 15,
    title: 'IFR pilot seeking 1/3 or 1/4 share near Austin (KAUS)',
    description: 'I\'m an instrument-rated pilot with 280 hours looking for a share in a well-maintained single near Austin. Flexible on make/model as long as it\'s IFR-equipped and airworthy. I fly about 15 hours a month, mostly weekends. Happy to split hangar and insurance costs.',
    contact_name: 'Alex R.',
    contact_email: 'alex@example.com',
    contact_method: 'email',
    contact_phone: null,
    status: 'active',
    poster_id: null,
  },
  {
    id: 'seek-2',
    created_at: '2026-06-03T00:00:00Z',
    updated_at: '2026-06-03T00:00:00Z',
    preferred_makes: ['Cirrus'],
    preferred_models: 'SR20, SR22',
    min_year: 2005,
    max_year: null,
    aircraft_category: 'sel',
    max_buy_in: 50000,
    max_monthly: 700,
    max_hourly: 150,
    home_airport: 'KFXE',
    airport_name: 'Fort Lauderdale Executive',
    city: 'Fort Lauderdale',
    state: 'FL',
    willing_to_travel_nm: 30,
    total_hours: 650,
    ratings_held: ['PPL', 'IFR', 'Cirrus Transition'],
    preferred_share_types: ['1/2', '1/3'],
    preferred_scheduling: null,
    intended_use: ['personal_travel', 'cross_country', 'instrument_currency'],
    hours_per_month: 25,
    title: 'Experienced Cirrus pilot seeking SR22 share at KFXE or nearby',
    description: 'Cirrus-typed pilot with 650 hours looking for an SR20 or SR22 half or third share in the Fort Lauderdale area. I fly cross-country trips regularly and keep my instrument currency current. Flexible on scheduling system — I have used both FlyingClub and Google Calendar. Let\'s talk!',
    contact_name: 'Priya N.',
    contact_email: 'priya@example.com',
    contact_method: 'both',
    contact_phone: '954-555-0211',
    status: 'active',
    poster_id: null,
  },
  {
    id: 'seek-3',
    created_at: '2026-06-07T00:00:00Z',
    updated_at: '2026-06-07T00:00:00Z',
    preferred_makes: ['Beechcraft', 'Piper', 'Cessna'],
    preferred_models: 'Bonanza, Debonair, Comanche, 182',
    min_year: 1990,
    max_year: null,
    aircraft_category: 'sel',
    max_buy_in: 35000,
    max_monthly: 500,
    max_hourly: 120,
    home_airport: 'KPAO',
    airport_name: 'Palo Alto Airport',
    city: 'Palo Alto',
    state: 'CA',
    willing_to_travel_nm: 40,
    total_hours: 420,
    ratings_held: ['PPL', 'IFR', 'Complex', 'High Performance'],
    preferred_share_types: ['1/2', '1/3'],
    preferred_scheduling: 'Google Calendar',
    intended_use: ['weekend_trips', 'cross_country', 'personal_travel'],
    hours_per_month: 20,
    title: 'Complex/HP-endorsed pilot looking for Bonanza or Comanche share near KPAO',
    description: 'Bay Area-based pilot with complex and high performance endorsements seeking a share in a faster single. Prefer retractable gear but will consider a strong fixed-gear like a 182 or Comanche. Available mostly weekends and occasional weekdays. I take maintenance seriously and am happy to be involved in the annual process.',
    contact_name: 'Wei C.',
    contact_email: 'wei@example.com',
    contact_method: 'email',
    contact_phone: null,
    status: 'active',
    poster_id: null,
  },
]
